name: montesori
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bubble: ^1.2.1
  flutter_swipe_detector: ^1.0.1
  rive: ^0.7.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"
  flutter_app_name: ^0.1.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# This is for launcher icon setup
flutter_icons:
  image_path: "assets/images/menu/ic_menu_logo.png" 
  android: true
  ios: true

# This is for App name
flutter_app_name:
  name: "Nido App"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/loading_screen/ic_loading_screen.png
      - assets/images/menu/ic_menu_background.png
      - assets/images/menu/ic_menu_angka.png
      - assets/images/menu/ic_menu_bentuk.png
      - assets/images/menu/ic_menu_warna.png
      - assets/images/menu/ic_menu_huruf.png
      - assets/images/menu/ic_menu_play.png
      - assets/images/menu/ic_menu_logo.png
      - assets/images/menu/ic_menu_pause.png
      - assets/images/menu/ic_menu_win_banner.png
      - assets/images/menu/ic_menu_win_star.png
      - assets/images/game_menu_screen/gs_angka.png
      - assets/images/game_menu_screen/gs_bentuk.png
      - assets/images/game_menu_screen/gs_huruf.jpg
      - assets/images/game_menu_screen/gs_warna.png
      - assets/images/angka/bg_angka.png
      - assets/images/angka/ic_angka_buto.png
      - assets/images/angka/ic_angka_buto_hurt.png
      - assets/images/angka/ic_angka_timunemas.png
      - assets/images/angka/ic_angka_biji.png
      - assets/images/guide/ic_arrow_angka.png
      - assets/images/guide/ic_arrow_warna.png
      - assets/animations/angka/swipeup.riv
      - assets/images/bentuk/ic_bentuk_star.png
      - assets/images/bentuk/ic_bentuk_triangle.png
      - assets/images/bentuk/ic_bentuk_circle.png
      - assets/images/bentuk/ic_bentuk_1.png
      - assets/images/bentuk/ic_bentuk_2.png
      - assets/images/bentuk/ic_bentuk_3.png
      - assets/images/bentuk/ic_bentuk_4.png
      - assets/images/bentuk/ic_bentuk_5.png
      - assets/images/bentuk/ic_bentuk_6.png
      - assets/images/bentuk/ic_bentuk_bg.png
      - assets/images/warna/ic_warna_1.png
      - assets/images/warna/ic_warna_2.png
      - assets/images/warna/ic_warna_3.png
      - assets/images/warna/ic_warna_4.png
      - assets/images/warna/ic_warna_5.png
      - assets/images/warna/ic_warna_6.png
      - assets/images/huruf/before/ic_huruf_a.png
      - assets/images/huruf/before/ic_huruf_b.png
      - assets/images/huruf/before/ic_huruf_c.png
      - assets/images/huruf/before/ic_huruf_d.png
      - assets/images/huruf/before/ic_huruf_e.png
      - assets/images/huruf/before/ic_huruf_f.png
      - assets/images/huruf/before/ic_huruf_g.png
      - assets/images/huruf/before/ic_huruf_h.png
      - assets/images/huruf/before/ic_huruf_i.png
      - assets/images/huruf/before/ic_huruf_j.png
      - assets/images/huruf/before/ic_huruf_k.png
      - assets/images/huruf/before/ic_huruf_l.png
      - assets/images/huruf/before/ic_huruf_m.png
      - assets/images/huruf/before/ic_huruf_n.png
      - assets/images/huruf/before/ic_huruf_o.png
      - assets/images/huruf/before/ic_huruf_p.png
      - assets/images/huruf/before/ic_huruf_q.png
      - assets/images/huruf/before/ic_huruf_r.png
      - assets/images/huruf/before/ic_huruf_s.png
      - assets/images/huruf/before/ic_huruf_t.png
      - assets/images/huruf/before/ic_huruf_u.png
      - assets/images/huruf/before/ic_huruf_v.png
      - assets/images/huruf/before/ic_huruf_w.png
      - assets/images/huruf/before/ic_huruf_x.png
      - assets/images/huruf/before/ic_huruf_y.png
      - assets/images/huruf/before/ic_huruf_z.png
      - assets/images/huruf/after/ic_huruf_a.png
      - assets/images/huruf/after/ic_huruf_b.png
      - assets/images/huruf/after/ic_huruf_c.png
      - assets/images/huruf/after/ic_huruf_d.png
      - assets/images/huruf/after/ic_huruf_e.png
      - assets/images/huruf/after/ic_huruf_f.png
      - assets/images/huruf/after/ic_huruf_g.png
      - assets/images/huruf/after/ic_huruf_h.png
      - assets/images/huruf/after/ic_huruf_i.png
      - assets/images/huruf/after/ic_huruf_j.png
      - assets/images/huruf/after/ic_huruf_k.png
      - assets/images/huruf/after/ic_huruf_l.png
      - assets/images/huruf/after/ic_huruf_m.png
      - assets/images/huruf/after/ic_huruf_n.png
      - assets/images/huruf/after/ic_huruf_o.png
      - assets/images/huruf/after/ic_huruf_p.png
      - assets/images/huruf/after/ic_huruf_q.png
      - assets/images/huruf/after/ic_huruf_r.png
      - assets/images/huruf/after/ic_huruf_s.png
      - assets/images/huruf/after/ic_huruf_t.png
      - assets/images/huruf/after/ic_huruf_u.png
      - assets/images/huruf/after/ic_huruf_v.png
      - assets/images/huruf/after/ic_huruf_w.png
      - assets/images/huruf/after/ic_huruf_x.png
      - assets/images/huruf/after/ic_huruf_y.png
      - assets/images/huruf/after/ic_huruf_z.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Rounded Mplus 1c
        fonts: 
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Thin.ttf
            weight: 100
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Light.ttf
            weight: 300
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Regular.ttf
            weight: 400
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Medium.ttf
            weight: 500
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Bold.ttf
            weight: 700
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/rounded_mplus_1c/MPLUSRounded1c-Black.ttf
            weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
